import requests
import json
import pandas as pd

def generate_siha_access_token(username, password):
    
    response = requests.get('http://localhost:5000/siha-api/clinicians/admin/login', auth=(username, password))
    access_token = response.text.replace('\n}\n', "").replace(' ','').replace('"', "").replace('{\n', '').replace('token:','')
    return access_token


def read_siha_activity_data(access_token=None, feature_name=None, patient_id=None, start_date=None, end_date=None):
    
    '''
    Parameters
    ----------
    access_token : string
    description: access_token generated by entering username and password in postman
    
    feature: string
    description: activity feature to fetch data for
    
    patient_id: string
    description: patient id to retreive data
    
    start_date: timestamp
    description: start date to fetch earliest available data
    
    end_date: timestamp
    description: end date to fetch latest available data
    
    Returns
    -------
    A python dict object
    '''
    
    url = 'http://localhost:5000/siha-api/v1/data/{}/patientid/{}/start/{}/end/{}'
    url = url.format(feature, patient_id, start_date, end_date)
    response = test_post_get_requests("GET", url, token, payload=None)
    return response

    
def read_data_json(dict_object, keys=None):
    
    df = pd.DataFrame()
    
    for key in keys:
        df['key'] = pd.DataFrame(data[key])
            

    return df
    

def read_data_json_file(filename, keys=None):
    
    with open('data.json') as json_file:
        dict_obj = json.load(json_file)
        
    
    return read_data_json(dict_obj, keys)

def read_fitbit_activity_data(access_token, refresh_token):
    #Need to play with FitBit API and authentication process 
    pass
